
String8 os_g_key_string_table[90] =
{
    Str8LitComp("Null"),
    Str8LitComp("Escape"),
    Str8LitComp("F1"),
    Str8LitComp("F2"),
    Str8LitComp("F3"),
    Str8LitComp("F4"),
    Str8LitComp("F5"),
    Str8LitComp("F6"),
    Str8LitComp("F7"),
    Str8LitComp("F8"),
    Str8LitComp("F9"),
    Str8LitComp("F10"),
    Str8LitComp("F11"),
    Str8LitComp("F12"),
    Str8LitComp("F13"),
    Str8LitComp("F14"),
    Str8LitComp("F15"),
    Str8LitComp("F16"),
    Str8LitComp("F17"),
    Str8LitComp("F18"),
    Str8LitComp("F19"),
    Str8LitComp("F20"),
    Str8LitComp("F21"),
    Str8LitComp("F22"),
    Str8LitComp("F23"),
    Str8LitComp("F24"),
    Str8LitComp("Grave Accent"),
    Str8LitComp("0"),
    Str8LitComp("1"),
    Str8LitComp("2"),
    Str8LitComp("3"),
    Str8LitComp("4"),
    Str8LitComp("5"),
    Str8LitComp("6"),
    Str8LitComp("7"),
    Str8LitComp("8"),
    Str8LitComp("9"),
    Str8LitComp("Minus"),
    Str8LitComp("Equal"),
    Str8LitComp("Backspace"),
    Str8LitComp("Delete"),
    Str8LitComp("Tab"),
    Str8LitComp("A"),
    Str8LitComp("B"),
    Str8LitComp("C"),
    Str8LitComp("D"),
    Str8LitComp("E"),
    Str8LitComp("F"),
    Str8LitComp("G"),
    Str8LitComp("H"),
    Str8LitComp("I"),
    Str8LitComp("J"),
    Str8LitComp("K"),
    Str8LitComp("L"),
    Str8LitComp("M"),
    Str8LitComp("N"),
    Str8LitComp("O"),
    Str8LitComp("P"),
    Str8LitComp("Q"),
    Str8LitComp("R"),
    Str8LitComp("S"),
    Str8LitComp("T"),
    Str8LitComp("U"),
    Str8LitComp("V"),
    Str8LitComp("W"),
    Str8LitComp("X"),
    Str8LitComp("Y"),
    Str8LitComp("Z"),
    Str8LitComp("Space"),
    Str8LitComp("Enter"),
    Str8LitComp("Ctrl"),
    Str8LitComp("Shift"),
    Str8LitComp("Alt"),
    Str8LitComp("Up"),
    Str8LitComp("Left"),
    Str8LitComp("Down"),
    Str8LitComp("Right"),
    Str8LitComp("Page Up"),
    Str8LitComp("Page Down"),
    Str8LitComp("Home"),
    Str8LitComp("End"),
    Str8LitComp("Forward Slash"),
    Str8LitComp("Period"),
    Str8LitComp("Comma"),
    Str8LitComp("Quote"),
    Str8LitComp("Left Bracket"),
    Str8LitComp("Right Bracket"),
    Str8LitComp("Left Mouse Button"),
    Str8LitComp("Middle Mouse Button"),
    Str8LitComp("Right Mouse Button"),
};

